# AUTOGENERATED! DO NOT EDIT! File to edit: ../bike_rental_pipeline.ipynb.

# %% auto 0
__all__ = ['jc_files']

# %% ../bike_rental_pipeline.ipynb 3
import seaborn as sns
import pandas as pd
from matplotlib import pyplot as plt
import glob

# %% ../bike_rental_pipeline.ipynb 7
jc_files = glob.glob(r'..\bike_rental_data\data\JC-2016**-citibike-tripdata.csv')
jc_files
