# AUTOGENERATED! DO NOT EDIT! File to edit: ../bike_rental_pipeline.ipynb.

# %% auto 0
__all__ = ['jc_files', 'df_jc']

# %% ../bike_rental_pipeline.ipynb 3
import seaborn as sns
import pandas as pd
from matplotlib import pyplot as plt
import glob

# %% ../bike_rental_pipeline.ipynb 6
import warnings

# Заранее отключим ворнинги
warnings.filterwarnings("ignore") # Заранее уберем ворнинги

# %% ../bike_rental_pipeline.ipynb 10
jc_files = glob.glob(r'..\bike_rental_data\data\JC-2016**-citibike-tripdata.csv')
jc_files

# %% ../bike_rental_pipeline.ipynb 11
#Citi Bike data from Jersey City

df_jc = []

# %% ../bike_rental_pipeline.ipynb 12
for file in jc_files:
    df_jc.append(pd.read_csv(file))

df_jc = pd.concat(df_jc).reset_index(drop=True)

# %% ../bike_rental_pipeline.ipynb 13
df_jc.columns = df_jc.columns.str.lower()
df_jc.columns = df_jc.columns.str.replace(' ', '_')

# %% ../bike_rental_pipeline.ipynb 14
# Print head of datasets for the 12 months of 2016 united

print('Initial data head:')
print()

df_jc.head(5)

# %% ../bike_rental_pipeline.ipynb 15
df_jc.describe()

# %% ../bike_rental_pipeline.ipynb 16
df_jc.info()

# %% ../bike_rental_pipeline.ipynb 17
# None check

(
    df_jc.isna()
    .sum()
    .sort_values(ascending=False)
)

# %% ../bike_rental_pipeline.ipynb 20
df_na.columns = df_na.columns.str.lower()
df_na.columns = df_na.columns.str.replace(' ', '_')

# %% ../bike_rental_pipeline.ipynb 21
# Print head of weather dataset

print('Initial data head:')
print()
df_na.head(5)

# %% ../bike_rental_pipeline.ipynb 22
df_na.describe()

# %% ../bike_rental_pipeline.ipynb 23
df_na.info()

# %% ../bike_rental_pipeline.ipynb 24
# None check

(
    df_na.isna()
    .sum()
    .sort_values(ascending=False)
)
